name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run:
    name: Run the action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./
        name: Compute diff
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
